import type {
  BankAccount,
  BudgetItem,
  CurrencyDefinition,
  Debt,
  IncomeEntry,
  IncomeSource,
  Investment,
  Transaction,
  WaterfallState,
} from "./types.ts";
import { addDaysIso, addMonthsIso, todayIso } from "./money.ts";

const CURRENCIES: CurrencyDefinition[] = [
  { code: "KES", name: "Kenyan Shilling", symbol: "KSh", decimalPlaces: 2, rateToBase: 1, isBase: true, kind: "FIAT", active: true },
  { code: "USD", name: "US Dollar", symbol: "$", decimalPlaces: 2, rateToBase: 129.3, isBase: false, kind: "FIAT", active: true },
  { code: "GBP", name: "British Pound", symbol: "£", decimalPlaces: 2, rateToBase: 174.68, isBase: false, kind: "FIAT", active: true },
  { code: "EUR", name: "Euro", symbol: "€", decimalPlaces: 2, rateToBase: 148.14, isBase: false, kind: "FIAT", active: true },
  { code: "CAD", name: "Canadian Dollar", symbol: "C$", decimalPlaces: 2, rateToBase: 91.38, isBase: false, kind: "FIAT", active: true },
  { code: "AED", name: "UAE Dirham", symbol: "د.إ", decimalPlaces: 2, rateToBase: 35.18, isBase: false, kind: "FIAT", active: true },
  { code: "ZAR", name: "South African Rand", symbol: "R", decimalPlaces: 2, rateToBase: 7.89, isBase: false, kind: "FIAT", active: true },
  { code: "TZS", name: "Tanzanian Shilling", symbol: "TSh", decimalPlaces: 0, rateToBase: 20.38, isBase: false, kind: "FIAT", active: true },
  { code: "RWF", name: "Rwandan Franc", symbol: "FRw", decimalPlaces: 0, rateToBase: 11.34, isBase: false, kind: "FIAT", active: true },
  { code: "JPY", name: "Japanese Yen", symbol: "¥", decimalPlaces: 0, rateToBase: 0.7967, isBase: false, kind: "FIAT", active: true },
];

const k = (major: number) => Math.round(major * 100);

function isoMonthsAgo(months: number, day: number, from = new Date()): string {
  const d = new Date(from);
  d.setMonth(d.getMonth() - months);
  d.setDate(day);
  return todayIso(d);
}

export function createSeed(now = new Date()): WaterfallState {
  const today = todayIso(now);
  const created = now.getTime() - 1000 * 60 * 60 * 24 * 140;

  const banks: BankAccount[] = [
    {
      id: 1,
      bankName: "Equity Bank",
      accountName: "Current",
      accountNumber: "0170294412",
      nickname: "Everyday",
      currencyCode: "KES",
      balanceMinor: k(62400),
      availableMinor: k(30400),
      reservedMinor: k(32000),
      active: true,
      isDefault: true,
      purpose: "SPENDING",
      accountType: "CURRENT",
      lastBalanceIso: today,
    },
    {
      id: 2,
      bankName: "M-PESA",
      accountName: "Mobile money",
      accountNumber: "0712 448 901",
      nickname: "M-PESA",
      currencyCode: "KES",
      balanceMinor: k(18420),
      availableMinor: k(18420),
      reservedMinor: 0,
      active: true,
      isDefault: false,
      purpose: "MPESA",
      accountType: "MOBILE",
      fulizaEnabled: true,
      fulizaOutstandingMinor: k(8000),
      fulizaLimitMinor: k(20000),
      fulizaRate: 0.01083,
      lastBalanceIso: today,
    },
    {
      id: 3,
      bankName: "NCBA",
      accountName: "Save",
      accountNumber: "100289331",
      nickname: "NCBA Save",
      currencyCode: "KES",
      balanceMinor: k(240000),
      availableMinor: 0,
      reservedMinor: k(240000),
      active: true,
      isDefault: false,
      purpose: "SAVINGS",
      accountType: "SAVINGS",
      lastBalanceIso: today,
    },
  ];

  const items: BudgetItem[] = [
    {
      id: 10,
      bucket: "NEED",
      label: "Rent",
      targetMinor: k(45000),
      currentMinor: k(45000),
      currencyCode: "KES",
      dueDateIso: today.slice(0, 8) + "01",
      priority: 1,
      recurring: true,
      frequencyMonths: 1,
      active: true,
      note: "Westlands studio",
      createdAt: created,
      category: "Rent",
    },
    {
      id: 11,
      bucket: "NEED",
      label: "Food",
      targetMinor: k(28000),
      currentMinor: k(8200),
      currencyCode: "KES",
      dueDateIso: addDaysIso(24, now),
      priority: 2,
      recurring: true,
      frequencyMonths: 1,
      active: true,
      note: null,
      createdAt: created,
      category: "Food",
    },
    {
      id: 12,
      bucket: "NEED",
      label: "Transport",
      targetMinor: k(18000),
      currentMinor: k(4100),
      currencyCode: "KES",
      dueDateIso: addDaysIso(24, now),
      priority: 3,
      recurring: true,
      frequencyMonths: 1,
      active: true,
      note: null,
      createdAt: created,
      category: "Transport",
    },
    {
      id: 13,
      bucket: "NEED",
      label: "Utilities",
      targetMinor: k(12000),
      currentMinor: k(2400),
      currencyCode: "KES",
      dueDateIso: addDaysIso(12, now),
      priority: 4,
      recurring: true,
      frequencyMonths: 1,
      active: true,
      note: "Power, water, fibre",
      createdAt: created,
      category: "Utilities",
    },
    {
      id: 14,
      bucket: "NEED",
      label: "Household",
      targetMinor: k(10000),
      currentMinor: k(1200),
      currencyCode: "KES",
      dueDateIso: addDaysIso(20, now),
      priority: 5,
      recurring: true,
      frequencyMonths: 1,
      active: true,
      note: null,
      createdAt: created,
      category: "Household",
    },
    {
      id: 15,
      bucket: "WANT",
      label: "Dining out",
      targetMinor: k(12000),
      currentMinor: k(1600),
      currencyCode: "KES",
      dueDateIso: addDaysIso(24, now),
      priority: 6,
      recurring: true,
      frequencyMonths: 1,
      active: true,
      note: null,
      createdAt: created,
      category: "Dining",
    },
    {
      id: 16,
      bucket: "WANT",
      label: "Personal care",
      targetMinor: k(10000),
      currentMinor: k(500),
      currencyCode: "KES",
      dueDateIso: addDaysIso(24, now),
      priority: 7,
      recurring: true,
      frequencyMonths: 1,
      active: true,
      note: null,
      createdAt: created,
      category: "Personal",
    },
    {
      id: 17,
      bucket: "WANT",
      label: "Data & airtime",
      targetMinor: k(10000),
      currentMinor: k(0),
      currencyCode: "KES",
      dueDateIso: addDaysIso(24, now),
      priority: 8,
      recurring: true,
      frequencyMonths: 1,
      active: true,
      note: null,
      createdAt: created,
      category: "Data",
    },
    {
      id: 20,
      bucket: "GOAL",
      label: "Japan Trip",
      targetMinor: k(150000),
      currentMinor: k(80000),
      currencyCode: "KES",
      dueDateIso: addDaysIso(48, now),
      priority: 1,
      recurring: false,
      frequencyMonths: 0,
      active: true,
      note: "Kyoto in November",
      createdAt: created,
      category: "Travel",
    },
    {
      id: 21,
      bucket: "GOAL",
      label: "Emergency fund",
      targetMinor: k(360000),
      currentMinor: k(240000),
      currencyCode: "KES",
      dueDateIso: null,
      priority: 1,
      recurring: false,
      frequencyMonths: 0,
      active: true,
      note: "Six months of needs",
      createdAt: created - 1000 * 60 * 60 * 24 * 180,
      category: "Savings",
    },
    {
      id: 23,
      bucket: "GOAL",
      label: "Birthday",
      targetMinor: k(15000),
      currentMinor: k(4000),
      currencyCode: "KES",
      dueDateIso: `${now.getFullYear()}-09-22`,
      priority: 2,
      recurring: true,
      frequencyMonths: 12,
      frequencyCode: "YEARLY",
      active: true,
      note: "Annual",
      createdAt: created,
      category: "BIRTHDAY",
    },
    {
      id: 22,
      bucket: "GOAL",
      label: "New camera",
      targetMinor: k(80000),
      currentMinor: k(12000),
      currencyCode: "KES",
      dueDateIso: addMonthsIso(5, now),
      priority: 3,
      recurring: false,
      frequencyMonths: 0,
      active: true,
      note: null,
      createdAt: created,
      category: "Gear",
    },
  ];
  const period = today.slice(0, 7);
  items.forEach((item) => {
    if (!item.periodKey) item.periodKey = item.frequencyMonths >= 12 ? today.slice(0, 4) : period;
  });

  const sources: IncomeSource[] = [
    {
      id: 30,
      label: "Nairobi Analytics",
      defaultBankId: 1,
      allowedScopes: ["NEED", "WANT", "GOAL", "BANK"],
      selectedItemIds: [],
      currencyCode: "KES",
      fxRateToBase: 1,
      active: true,
    },
    {
      id: 31,
      label: "Studio retainers",
      defaultBankId: 1,
      allowedScopes: ["GOAL", "BANK"],
      selectedItemIds: [20, 21],
      currencyCode: "KES",
      fxRateToBase: 1,
      active: true,
    },
  ];

  const incomeEntries: IncomeEntry[] = [5, 4, 3, 2, 1, 0].map((monthsAgo, i) => ({
    id: 40 + i,
    sourceId: 30,
    sourceLabel: "Nairobi Analytics",
    amountMinor: k(180000),
    currencyCode: "KES",
    originalAmountMinor: k(180000),
    originalCurrencyCode: "KES",
    receivedIso: isoMonthsAgo(monthsAgo, 1, now),
    fxRateToBase: 1,
    note: "Monthly salary",
    createdAt: created + i,
  }));
  incomeEntries.push({
    id: 46,
    sourceId: 31,
    sourceLabel: "Studio retainers",
    amountMinor: k(24000),
    currencyCode: "KES",
    originalAmountMinor: k(24000),
    originalCurrencyCode: "KES",
    receivedIso: isoMonthsAgo(0, 3, now),
    fxRateToBase: 1,
    note: "Brand stills",
    createdAt: now.getTime() - 86400000 * 3,
  });

  const txn = (
    id: number,
    kind: Transaction["kind"],
    payee: string,
    category: string,
    major: number,
    daysAgo: number,
    itemId: number | null,
    accountId = 2,
  ): Transaction => ({
    id,
    kind,
    payee,
    category,
    amountMinor: k(major),
    currencyCode: "KES",
    accountId,
    itemId,
    isoDate: addDaysIso(-daysAgo, now),
    note: null,
    createdAt: now.getTime() - daysAgo * 86400000,
  });

  const transactions: Transaction[] = [
    txn(100, "expense", "Naivas Westlands", "Food", 2400, 1, 11),
    txn(101, "expense", "Carrefour Two Rivers", "Food", 3100, 3, 11),
    txn(102, "expense", "Java House", "Food", 680, 4, 11),
    txn(103, "expense", "Wambui grocer", "Food", 2020, 5, 11),
    txn(104, "expense", "Little Cab", "Transport", 850, 1, 12),
    txn(105, "expense", "Fuel — Total", "Transport", 2400, 2, 12),
    txn(106, "expense", "Matatu week", "Transport", 850, 5, 12),
    txn(107, "expense", "KPLC token", "Utilities", 1400, 2, 13),
    txn(108, "expense", "Safaricom fibre", "Utilities", 1000, 4, 13),
    txn(109, "expense", "Carrefour home", "Household", 1200, 5, 14),
    txn(110, "expense", "Cultiva", "Dining", 1600, 3, 15),
    txn(111, "expense", "Barber", "Personal", 500, 6, 16),
    txn(112, "expense", "Landlord", "Rent", 45000, Number(today.slice(8, 10)) - 1 || 1, 10, 1),
    txn(113, "income", "Nairobi Analytics", "Salary", 180000, Number(today.slice(8, 10)) - 1 || 1, null, 1),
    txn(114, "income", "Studio retainers", "Freelance", 24000, 3, null, 1),
    {
      ...txn(120, "expense", "Naivas", "Food", 3600, 20, 11),
      isoDate: isoMonthsAgo(1, 8, now),
    },
    {
      ...txn(121, "expense", "Carrefour", "Food", 3400, 22, 11),
      isoDate: isoMonthsAgo(1, 14, now),
    },
    {
      ...txn(122, "expense", "Market", "Food", 2318, 24, 11),
      isoDate: isoMonthsAgo(1, 21, now),
    },
    {
      ...txn(123, "expense", "Fuel", "Transport", 5200, 20, 12),
      isoDate: isoMonthsAgo(1, 9, now),
    },
    {
      ...txn(124, "expense", "Little Cab", "Transport", 1600, 22, 12),
      isoDate: isoMonthsAgo(1, 18, now),
    },
    {
      ...txn(125, "expense", "KPLC", "Utilities", 1800, 21, 13),
      isoDate: isoMonthsAgo(1, 11, now),
    },
    {
      ...txn(126, "expense", "Landlord", "Rent", 45000, 25, 10, 1),
      isoDate: isoMonthsAgo(1, 1, now),
    },
    {
      ...txn(127, "income", "Nairobi Analytics", "Salary", 180000, 25, null, 1),
      isoDate: isoMonthsAgo(1, 1, now),
    },
  ];

  const investments: Investment[] = [
    {
      id: 60,
      name: "CIC Money Market",
      kind: "MMF",
      valueMinor: k(45000),
      costMinor: k(42000),
      apr: 0.102,
      currencyCode: "KES",
      note: "Daily liquidity",
    },
    {
      id: 61,
      name: "Stima Sacco shares",
      kind: "SACCO",
      valueMinor: k(120000),
      costMinor: k(100000),
      apr: 0.08,
      currencyCode: "KES",
      note: "Dividends in December",
    },
  ];

  const debts: Debt[] = [
    {
      id: 70,
      name: "Car service loan",
      remainingMinor: k(31000),
      originalMinor: k(80000),
      paymentMinor: k(20000),
      apr: 0.14,
      dueDateIso: addDaysIso(24, now),
      currencyCode: "KES",
    },
  ];

  return {
    profile: {
      displayName: "Ivan",
      birthdayIso: `${now.getFullYear()}-09-22`,
      baseCurrencyCode: "KES",
      themeMode: "DARK",
      tightness: "managing",
      dependents: "Just me",
      payDay: "25",
    },
    items,
    banks,
    sources,
    incomeEntries,
    transactions,
    events: [
      {
        id: 80,
        incomeEntryId: 45,
        sourceLabel: "Nairobi Analytics",
        totalIncomeMinor: k(180000),
        bufferMinor: k(9000),
        bankMinor: k(18420),
        currencyCode: "KES",
        summary: "Salary allocated across needs, goals, and Equity.",
        createdAt: now.getTime() - 86400000 * (Number(today.slice(8, 10)) - 1 || 1),
        lines: [
          { itemId: 10, label: "Rent", bucket: "NEED", kind: "CURRENT", amountMinor: k(45000), remainingAfterMinor: 0, dueDateIso: null, note: "Fully funded" },
          { itemId: 11, label: "Food", bucket: "NEED", kind: "CURRENT", amountMinor: k(28000), remainingAfterMinor: 0, dueDateIso: null, note: "Fully funded" },
          { itemId: 12, label: "Transport", bucket: "NEED", kind: "CURRENT", amountMinor: k(18000), remainingAfterMinor: 0, dueDateIso: null, note: "Fully funded" },
          { itemId: 20, label: "Japan Trip", bucket: "GOAL", kind: "CURRENT", amountMinor: k(22000), remainingAfterMinor: k(70000), dueDateIso: addDaysIso(48, now), note: "Weighted allocation" },
          { itemId: 21, label: "Emergency fund", bucket: "GOAL", kind: "CURRENT", amountMinor: k(39600), remainingAfterMinor: k(120000), dueDateIso: null, note: "Weighted allocation" },
        ],
      },
    ],
    currencies: CURRENCIES,
    investments,
    debts,
    lastPlan: null,
    lastDecisionNotes: [],
    lastConfidence: "high",
    lastReallocation: null,
    prefs: {
      fundingMode: "SMART",
      minReserveMinor: k(20000),
      wantsCapMinor: k(30000),
      onboarded: true,
      learnedCaps: { entertainment: k(5000) },
      lastIncomeLabel: "Salary",
      lastIncomeMinor: k(180000),
    },
    nextId: 200,
  };
}

export function createFresh(now = new Date()): WaterfallState {
  const empty = createSeed(now);
  return {
    ...empty,
    profile: {
      displayName: "",
      birthdayIso: null,
      baseCurrencyCode: "KES",
      themeMode: "DARK",
    },
    items: [],
    banks: [],
    sources: [],
    incomeEntries: [],
    transactions: [],
    events: [],
    investments: [],
    debts: [],
    lastPlan: null,
    lastDecisionNotes: [],
    lastConfidence: "",
    lastReallocation: null,
    prefs: {
      fundingMode: "SMART",
      minReserveMinor: 0,
      wantsCapMinor: null,
      onboarded: false,
      learnedCaps: {},
      lastIncomeLabel: "",
      lastIncomeMinor: 0,
    },
    nextId: 1,
  };
}

export const EMPTY_COPY_SEED_NOTE = "offline-local";
